### PR TITLE
Fixed #43 by adding connectionType to the SCM plugin configuration.

### LINKED ISSUE #43: tag-master goal unable to push to BitBucket
When merging branches into master with the tag-master goal enabled I get:

```
[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/myProject/workspace && git push http:********@git.myServer.com/myProject.git refs/tags/0.0.37
[INFO] Working directory: /var/lib/jenkins/jobs/myProject/workspace
[ERROR] Provider message:
[ERROR] The git-push command failed.
[ERROR] Command output:
[ERROR] fatal: could not read Password for 'http://jenkins@git.myServer.com': No such device or address
```

In addition to the gitflow-helper-maven-plugin my pom.xml I also has:

```
<project.scm.id>myServerId</project.scm.id>
...
<scm>
    <connection>scm:git:http://jenkins@git.myServer.com/scm/myProject.git</connection>
    <developerConnection>scm:git:http://jenkins@git.myServer.com/scm/myProject.git</developerConnection>
    <tag>HEAD</tag>
</scm>
```

and in the settings.xml of the docker container running Jenkins I have:

```
<servers>
    <server>
        <id>myServerId</id>
        <username>jenkins</username>
        <password>myPassword</password>
    </server>
    ...
</servers>
```

I notice that when I use the maven-release-plugin my git push looks more like:
`[INFO] Executing: /bin/sh -c cd /var/lib/jenkins/jobs/myProject/workspace && git push http://jenkins:********@git.myServer.com/scm/myProject.git refs/tags/0.0.37`
that is to say, it has "//jenkins:" after the username. I'm guessing that somehow my username and password from the settings.xml is not being added to the push request when using gitflow-helper-maven-plugin.

### PR DESCRIPTION
**Pull request by raehalme**
Also added a check that the gitURL does not already contain "scm:git:" which may be the case when the value is obtained from the POM.

### CODE REVIEW

File: src/main/java/com/e_gineering/maven/gitflowhelper/TagMasterMojo.java [hunk 1]
```diff
@@ -47,6 +47,9 @@ protected void execute(final GitBranchType type, final String gitBranch, final S
                 gitURLExpression = "${env.GIT_URL}";
             }
             String gitURL = resolveExpression(gitURLExpression);
+            if (!gitURL.startsWith("scm:git:")) {
```
Comment (tkelley-eg) [inline src/main/java/com/e_gineering/maven/gitflowhelper/TagMasterMojo.java]: Is there any chance this could come through as upper case?

Comment (raehalme) [inline src/main/java/com/e_gineering/maven/gitflowhelper/TagMasterMojo.java]: I did some testing with `scm:validate` and both the `scm:` prefix and the provider are case-sensitive and must be lowercase:

```
[ERROR] Validation of scm url connection (project.scm.developerConnection) failed :
[ERROR] The scm url must start with 'scm:'.
[ERROR] No such provider installed 'GIT'.
[ERROR] The invalid scm url connection: 'SCM:GIT:ssh://git@xxx/yyy/zzz.git'.
```

So I guess it should be safe to compare with lower case only.
