### PR TITLE
Fix handling of maven aggregator projects with no attachments

### LINKED ISSUE #44: promote-master on multi module projects
I am trying to run a mvn deploy on a multi module project.
Used gitflow-helper-maven-plugin version is 1.5.0.

Project structure is like this:
parent-pom
- module a
- module b

When I do a mvn deploy on the development branch the staging to our nexus fails with 
a 400 - BadRequest error. Reason seems to be that the process tries to upload some module-catalog.txt file.

After some search I figured out this information seems to be created during 
AbstractGitflowBasedRepositoryMojo#attachArtifactCatalog which is called when 
PromoteMasterMojo#execute method is invoked.

The output on the commandline shows:
[INFO] No primary artifact to catalog, cataloging attached artifacts instead.

I added some additional output to the 'attachArtifactCatalog ' method and could verify
that the project.getAttachedArtifacts() does return an empty list. 
This ends up in the creation of an empty file, which is later uploaded by the maven-deploy-plugin.
As this file is empty, the request does not contain any data and thus is rejected by nexus.

I hope somebody here has an idea whether this is a configuration issue or whether this is bug in the plugin.

The javadoc in the PromoteMasterMojo does not specify anything about doing something on 
a devopment branch, but the execute handels this case the same way as for hotfixes and releases.

After removing the respective case statement I could at least build the module normally. 
I have yet to test what happens on hotfix or release branches.

Edit:
I forgot to mention that the upload of the catalog.txt happens before the sub modules are actually build.

### PR DESCRIPTION
**Pull request by ukcrpb6**
Updates AbstractGitFlowBasedRepositoryMojo to Fix #44
Updates pom.xml to add expected code level (inferred from usage of `Files.createTempDirectory` which is `@since 1.7`)
Updates AbstractGitFlowBasedRepositoryMojo to 1.7 compatibility

Pertaining to #44:

When a pom type artifact is processed, whilst the project artifact has a value it does not have a file and therefore the main artifact is not added to the catalog, this is correct behaviour. However since neither the primary artifact nor the attached artifacts contribute any entries to the catalog this results in an empty file being sent to the repository. Certain repositories, I have tested under nexus 1.9.1, do not allow empty artifacts to be uploaded and therefore this results in an error when processing the promote-master mojo.

This can be resolved by adding a section header to the catalog such that it is of the form:

```
[artifacts]
group:artifact:extension:classifier-1:version
group:artifact:extension:classifier-2:version
```

with this the empty version becomes

```
[artifacts]
```

and thus behaves as expected

### CODE REVIEW

**Comment by bvarner** [comment]
Excellent catch. Thanks for tracking this down!

File: src/main/java/com/e_gineering/maven/gitflowhelper/AbstractGitflowBasedRepositoryMojo.java [hunk 1]
```diff
@@ -288,24 +265,37 @@ protected void attachExistingArtifacts(final String sourceRepository, final bool
...
-                String coords = null;
+                String coords;
+                boolean firstLine = true;
                 while ((coords = reader.readLine()) != null) {
-                    if (!coords.trim().isEmpty()) {
-                        // And add a new ArtifactRequest
-                        requiredArtifacts.add(new ArtifactRequest(new DefaultArtifact(coords.trim()), remoteRepositories, null));
+                    coords = coords.trim();
+
+                    // test for catalog header for bacvkwards compatibility
```
Comment (bvarner) [inline src/main/java/com/e_gineering/maven/gitflowhelper/AbstractGitflowBasedRepositoryMojo.java]: 👍
